apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 860098129225.dkr.ecr.us-east-1.amazonaws.com/bar:1.0
        ports:
        - containerPort: 5002
        env:
        - name: MYSQL_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: MYSQL_DATABASE_USER
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: MYSQL_DATABASE_HOST
        - name: MYSQL_DATABASE_DB
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: MYSQL_DATABASE_DB
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: MYSQL_DATABASE_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: project-secret
              key: MYSQL_ROOT_PASSWORD
