apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statfulset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-svc
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-contianer
        image: mysql:latest
        ports:
        - containerPort: 3306
          
        env:
       
     
          - name: MYSQL_DATABASE_DB
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: MYSQL_DATABASE_DB
          
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: project-secret
                key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
