apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql-svc"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_DATABASE_USER
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: MYSQL_DATABASE_USER
          - name: MYSQL_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: MYSQL_DATABASE_HOST
          - name: MYSQL_DATABASE_DB
            valueFrom:
              configMapKeyRef:
                name: project-configmap
                key: MYSQL_DATABASE_DB
          - name: MYSQL_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: project-secret
                key: MYSQL_DATABASE_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: project-secret
                key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
