version: '3.9'
services:
  flask_app:
    build: .
    ports:
      - "5002:5002"
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_DB: BucketList
      MYSQL_DATABASE_HOST: mysql
    depends_on:
      - mysql

  mysql:
       image: mysql:latest
       ports:
         - "3306:3306"

       environment:
         MYSQL_ROOT_PASSWORD: root
       volumes: 
         - ./MySQL_Queries:/docker-entrypoint-initdb.d  
          

